### ISSUE TITLE
simple objects exercise 

### ISSUE THREAD

**Issue by js08** [sporto/planetproto#18]
Hi,

https://github.com/sporto/planetproto/blob/master/exercises/010_simple_objects/solution/solution.js
I used the exact solution in the above link 

But I am seeing an error.
Providing the error below. Can you tell me how to fix it.

C:\Users\Desktop\node-school\planet-proto\010.js:5
claim(robot.smart, true);
^
ReferenceError: claim is not defined
    at Object.<anonymous> (C:\Users\Desktop\node-school\planet-proto\010.js:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by tyleronrails** [comment]
I had the same issue. After I reinstalled node everything started working. I used this commands:
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

**Comment by marcospolanco** [comment]
Still same issue.
