### ISSUE TITLE
Proto exercice

### ISSUE THREAD

**Issue by marianar97** [sporto/planetproto#27]
I haven't been able to complete the Proto task

It says 
// -> Make machine the prototype of robot

// -> Make robot the prototype of robby

How do I solve it?

Thanks

**Comment by sporto** [comment]
-> Make machine the prototype of robot
```
robot.__proto__ = machine;
```

-> Make robot the prototype of robby
```
robby.__proto__ = robot;
```

**Comment by sporto** [comment]
Makes sense?

**Comment by arnitkun** [comment]
Sorry to necro this issue, but I seem to have error in this exercise and can't figure out why.

```
// -> Create a machine object
//    with a property motors = 4
var machine = {motors: 4}

// -> Create a robot object
//    with a property friendly = true
var robot = {friendly: true}

// -> Create a robby object
var robby = {}

// -> Make machine the prototype of robot
robot.__proto__ = machine

// -> Make robot the prototype of robby
robby.__proto__ = robot

// -> What is `robby.motors`?
claim(robby.motors, 4);

// -> What is `robby.friendly`?
claim(robby.friendly, true);


// ------------------------------------------------
// Common JS exports for verification, don't modify
module.exports = {
	machine: machine,
	robot:   robot,
	robby:   robby
}

```

I am getting the following error: 

```
ReferenceError: robby is not defined
    at Object.<anonymous> (/Users/postman/postman-app/020.js:19:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/postman/.npm-global/lib/node_modules/planetproto/node_modules/workshopper-wrappedexec/exec-wrap.js:87:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "4 == 4 => true"
                                       !=    ""

────────────────────────────────────────────────────────────────────────────────
```

..which means the object is not created.(?)
